[2023-06-15T10:33:23.781+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: postgres_task.create_table manual__2023-06-15T10:33:22.735037+00:00 [queued]>
[2023-06-15T10:33:23.793+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: postgres_task.create_table manual__2023-06-15T10:33:22.735037+00:00 [queued]>
[2023-06-15T10:33:23.795+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T10:33:23.796+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-15T10:33:23.797+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T10:33:23.817+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table> on 2023-06-15 10:33:22.735037+00:00
[2023-06-15T10:33:23.827+0000] {standard_task_runner.py:55} INFO - Started process 313 to run task
[2023-06-15T10:33:23.837+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_task', 'create_table', 'manual__2023-06-15T10:33:22.735037+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/postgres.py', '--cfg-path', '/tmp/tmpzkwygrg3']
[2023-06-15T10:33:23.840+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask create_table
[2023-06-15T10:33:23.975+0000] {task_command.py:389} INFO - Running <TaskInstance: postgres_task.create_table manual__2023-06-15T10:33:22.735037+00:00 [running]> on host 33b865d2e169
[2023-06-15T10:33:24.047+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_task
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T10:33:22.735037+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T10:33:22.735037+00:00
[2023-06-15T10:33:24.049+0000] {sql.py:253} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS timestamps (
                curr_time TIMESTAMP
            );
        
[2023-06-15T10:33:24.081+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 254, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-06-15T10:33:24.085+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=postgres_task, task_id=create_table, execution_date=20230615T103322, start_date=20230615T103323, end_date=20230615T103324
[2023-06-15T10:33:24.096+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task create_table (The conn_id `postgres` isn't defined; 313)
[2023-06-15T10:33:24.130+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-15T10:33:24.150+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
